matrix:
  include:
    - language: c
      compiler:
        - clang
        - gcc
      dist: trusty
      script:
        - rake ci_build_posix
    - language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:latest bash
        - docker exec -it emscripten apt-get update
        - docker exec -it emscripten apt-get -y install rake
        - docker exec -it emscripten npm install uglify-js -g
      script:
        - docker exec -it -e PATH=${PATH}:/emsdk_portable/node/bin emscripten rake ci_build_js
    - language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:latest bash
        - docker exec -it emscripten apt-get update
        - docker exec -it emscripten apt-get -y install rake
      script:
        - docker exec -it emscripten rake ci_build_wasm
