matrix:
  include:
    - language: c
      compiler:
        - clang
        - gcc
      dist: trusty
      script:
        - cd posix
        - rake
        - rake test
    - language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd)/..:/src trzeci/emscripten:latest bash
      script:
        - cd js
        - docker exec -it emscripten apt-get rake
        - docker exec -it emscripten rake
        - node test_node.js
    - language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:latest bash
      script:
        - cd wasm
        - docker exec -it emscripten apt-get rake
        - docker exec -it emscripten rake
        - node test_node.js
