matrix:
  include:
    - language: c
      compiler:
        - clang
        - gcc
      dist: trusty
      script:
        - cd posix
        - rake
        - rake test
    - language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:latest bash
        - docker exec -it emscripten apt-get update
        - docker exec -it emscripten apt-get -y install rake
      script:
        - docker exec -it -e PATH=${PATH}:/emsdk_portable/node/bin -w /src/js emscripten rake clean default
        - cd js
        - node test_node.js
    - language: node_js
      node_js:
        - node
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:latest bash
        - docker exec -it emscripten apt-get update
        - docker exec -it emscripten apt-get -y install rake
      script:
        - docker exec -it -w /src/wasm emscripten rake clean default
        - cd wasm
        - node test_node.js
